### ISSUE TITLE
Scholar skeleton + upgrades = RuntimeException

### ISSUE THREAD

**Issue by irudi** [OleVik/grav-theme-scholar#27] opened 2021-08-10 13:16 UTC
Similar to #8: after having tried all kinds of ways of installing Scholar and get some docs pages working I opted for the skeleton route.

Skeleton worked fine. I've updated my content, docs section was working.

Updating to Grav v1.7.18, updating all plugins and themes (including Scholar) - RuntimeException when try to open the docs section :-( 

RuntimeException (400)
Template "docs.html.twig" is not defined.

**Comment by irudi** [comment] 2021-08-10 19:13
No, I've reduced it to 

```
components:
  - blog
  - docs
```

**Comment by OleVik** [comment] 2021-08-10 19:32
Hmm, [this](https://github.com/OleVik/grav-theme-scholar/blob/master/templates/default.html.twig#L42-L44) or [this](https://github.com/OleVik/grav-theme-scholar/blob/master/components/docs/docs.html.twig#L93-L95) should not fire if `what-links-here` is not in `theme.components` as a list-item. Does it work if you include it?

I might have to investigate further to see why it doesn't work as intended.

**Comment by irudi** [comment] 2021-08-10 19:54
Sorry, we have misunderstood each other.

The `what-links-here` error occurs only if I had all components enabled. 
But I've removed all but `blog` and `docs` again - because I just need `docs` at the moment.

**Comment by OleVik** [comment] 2022-06-25 14:58
This should be fixed by [v3.0.3](https://github.com/OleVik/grav-theme-scholar/releases/tag/3.0.3).

**Closed by OleVik** 2022-06-25 14:58 UTC
Labels: bug
